name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job:
    name: ${{ matrix.os}}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies with vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S . -DCMAKE_TOOLCHAIN_FILE="$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake"

    - name: Build
      run: cmake --build ${{github.workspace}}/build
      
    - name: Create Artifact
      run: |
        mkdir ${{matrix.os}}-release
        cp build/weighterm ${{matrix.os}}-release
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}-release
        path: ${{matrix.os}}-release
