name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  CONAN_USER_HOME: "/conan"

jobs:
  job:
    name: ${{ matrix.os}}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            output-path: "build/weighterm/bin"
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies with conan
      shell: bash
      run: |
        mkdir ${{ env.CONAN_USER_HOME }}
        mkdir build
        cd build
        pip install conan
        CONAN_USER_HOME=${{ env.CONAN_USER_HOME }} conan install .. --build missing

    - name: Configure CMake
      run: CONAN_USER_HOME=${{ env.CONAN_USER_HOME }} cmake -B ${{github.workspace}}/build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: CONAN_USER_HOME=${{ env.CONAN_USER_HOME }} cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      
    - name: Create Artifact
      run: |
        mkdir ${{matrix.os}}-release
        cp ${{matrix.output-path}} ${{matrix.os}}-release -r
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}-release
        path: ${{matrix.os}}-release
