name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  job:
    name: ${{ matrix.os}}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies using Conan
      run: |
        pip install conan
        mkdir build
        cd build
        conan install .. --build=missing

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build
      
    - name: Create Artifact
      run: |
        mkdir ${{matrix.os}}-release
        echo "Files in build directory"
        ls build
        cp build/hololive-tetris* ${{matrix.os}}-release
        cp images -r ${{matrix.os}}-release
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}-release
        path: ${{matrix.os}}-release
