name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  job:
    name: ${{ matrix.os}}-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            output-path: "build/weighterm"
    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies with vcpkg
      shell: bash
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        VCPKG_FEATURE_FLAGS=manifests ./vcpkg/vcpkg install

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S . -DCMAKE_TOOLCHAIN_FILE="$(pwd)/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      
    - name: Create Artifact
      run: |
        mkdir ${{matrix.os}}-release
        cp ${{matrix.output-path}} ${{matrix.os}}-release -r
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{matrix.os}}-release
        path: ${{matrix.os}}-release
